// Code generated by Slice Machine. DO NOT EDIT.

import BigText from './BigText';
import Image from './Image';
import TitleText from './TitleText';

export {
	BigText,
	Image,
	TitleText,
};

export const components = {
	big_text: BigText,
	image: Image,
	title_text: TitleText,
};
