// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  big_text: dynamic(() => import("./BigText")),
  image: dynamic(() => import("./Image")),
  text: dynamic(() => import("./Text")),
  title_text: dynamic(() => import("./TitleText")),
};
